name = "example-repo"
description = "Example repository with modules"

[default]
origin = "https://github.com/guibais/boil-test-repo.git"
files = ["**/*.md"]
ignore = ["**/skip.md"]

[modules.auth]
description = "Authentication module"
refs = ["auth-branch"]

[modules.user]
description = "User module"
refs = ["user-branch"]
dependencies = ["auth"]

[modules.payment]
description = "Payment module"
refs = ["payment-branch"]
dependencies = ["user"]
path = "custom-folder/payment"
files = ["modules/*.md"]
ignore = ["modules/secret.md"]
