name: CI

on:
  push:
    branches: [main, master, "**/*"]
  pull_request:
    branches: [main, master, "**/*"]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage/
          if-no-files-found: ignore

  publish:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Determine and bump version (Conv. Commits, max(registry, local))
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "Commit message: $COMMIT_MSG"
          BUMP="patch"
          if echo "$COMMIT_MSG" | grep -Eqi 'BREAKING CHANGE|!:'; then BUMP="major"; fi
          if echo "$COMMIT_MSG" | grep -Eqi '^feat|\sfeat'; then BUMP="minor"; fi
          echo "Bump type: $BUMP"

          REG_VER=$(npm view boilit version 2>/dev/null || echo "0.0.0")
          LOCAL_VER=$(node -p "require('./package.json').version")
          echo "Registry version: $REG_VER"
          echo "Local version:    $LOCAL_VER"

          # Decide BASE as the greater of REG_VER and LOCAL_VER
          if npx -y semver -r ">=$LOCAL_VER" "$REG_VER" >/dev/null 2>&1; then
            BASE="$REG_VER"
          else
            BASE="$LOCAL_VER"
          fi
          echo "Base version:     $BASE"

          NEXT=$(npx -y semver "$BASE" -i "$BUMP")
          echo "Next version:     $NEXT"

          npm version "$NEXT" --no-git-tag-version

      - name: Build
        run: npm run build --if-present

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
