name: CI

on:
  push:
    branches: [main, master, "**/*"]
  pull_request:
    branches: [main, master, "**/*"]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage/
          if-no-files-found: ignore

  publish:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Determine and bump version (Conv. Commits)
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "Commit message: $COMMIT_MSG"
          BUMP="patch"
          if echo "$COMMIT_MSG" | grep -Eqi 'BREAKING CHANGE|!:'; then BUMP="major"; fi
          if echo "$COMMIT_MSG" | grep -Eqi '^feat|\sfeat'; then BUMP="minor"; fi
          echo "Bumping version: $BUMP"
          npm version "$BUMP" --no-git-tag-version
          node -e "console.log('New version:', require('./package.json').version)"

      - name: Build
        run: npm run build --if-present

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
